### ISSUE TITLE
Access Service under Port 3000 in Docker Image not Possible

### ISSUE THREAD

**Issue by Beleggrodion** [matrix-org/matrix-user-verification-service#33]
I tried to setup this docker image on our docker server on which docker and jitsi is running. i added this to the docker-compose file.

```
  matrix-user-verification-service:
    depends_on:
      - synapse
    image: matrixdotorg/matrix-user-verification-service:branch-master
    restart: unless-stopped
    networks:
      - matrix
    ports:
      - 3000:3000
    environment:
      - UVS_ACCESS_TOKEN
      - UVS_HOMESERVER_URL
      - UVS_DISABLE_IP_BLACKLIST
      - UVS_LISTEN_ADDRESS
      - UVS_OPENID_VERIFY_SERVER_NAME
      - UVS_PORT
      - UVS_LOG_LEVEL
```
To the ENV Konfiguration (I Use Portainer) i added:
UVS_ACCESS_TOKEN = sometoken
UVS_HOMESERVER_URL = https://matrix.domain.com
UVS_DISABLE_IP_BLACKLIST = true
UVS_OPENID_VERIFY_SERVER_NAME = matrix.domain.com
UVS_LOG_LEVEL = debug

I see that now something is running under port "3000" but connect to it is not possible.

root@srv01:/data/docker-data# nc localhost 3000
POST /verify/user
root@srv01:/data/docker-data#

The same when i first  try to set "Authorization: Bearer sometoken" after connect.

The docker log file only show's me

```
> matrix-user-verification-service@2.0.0 start /app
> node src/app.js
{
  level: 'info',
  message: 'Attempting to listen on 127.0.0.1:3000',
  timestamp: '2023-01-04T11:46:04.224Z'
}
{
  level: 'info',
  message: 'Verify user service listening at 127.0.0.1:3000',
  timestamp: '2023-01-04T11:46:04.229Z'
}
```

and no connection attempt.  Do i something wrong with my configuration?
